### ISSUE TITLE
Notify users when they are switched to resume another top intent

### ISSUE THREAD

**Issue by grumo** [menchdotcom/source#2365]
If a student has partially completed a top intent and then changes the priority of top intents in their Action Plan, once they have completed the new priority they are taken to the next uncompleted intent from the former top priority without warning.
The personal assistant should notify users that they have switched top intents and have a "next" button to resume completing that intent tree.

**Comment by shervine** [comment]
@grumo Yes this would be helpful...

**Comment by shervine** [comment]
This requires Log User Intention Completion History V1 #2478

**Comment by shervine** [comment]
Merging into Completion Feedback & Share Page #3037
